### ISSUE TITLE
USE 3.0.1.1 says Invalid region! Valid regions are:

### ISSUE THREAD

**Issue by TaChao** [zoltx23/3DNUS#13]
use title 11.1.0-34J

**Comment by zoltx23** [comment]
Sorry for the late reply. Support for 3DNUS these days is limited, and I hardly work on it. 

Although, I was able to download the Firmware that you were trying to download; without any issues. 

Again, sorry for the late reply. 

![image](https://user-images.githubusercontent.com/7658605/28143853-def13600-6735-11e7-9de3-57ac61f04cbc.png)
