### ISSUE TITLE
Can't download System Title ID?

### ISSUE THREAD

**Issue by JKC-A9LH** [zoltx23/3DNUS#14]
l think if the Title ID is purely number, it will be ok. However the Title ID has capital letters, it will has a wrong? Or it's my fault l want to know~

**Comment by zoltx23** [comment]
Sorry for the late reply. But, some Title ID's have Capital letters. Also, telling me the Title ID would be useful. 

There shouldn't be any issues if you're simply coping and pasting the ID into 3DNUS, then downloading.
