### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by LeafAce** [zoltx23/3DNUS#15]
Is this a pc app? How do I open it? If it is for 3ds (which I doubt it is) how do I make it?

**Comment by zoltx23** [comment]
This is a PC executable (for Windows XP and above; both x86 and x64.) 
It is not designed to run on a 3DS, but allows you to download and pack 3DS Titles and Firmwares. 

Please consider reading the Readme on the root of the Repository before asking any questions.
