### ISSUE TITLE
System Data Archives refuse to download

### ISSUE THREAD

**Issue by v0idst4r** [zoltx23/3DNUS#16]
Trying input "0004800F484E4841 v11264" (DS Card whitelist) or "0004800F484E4C41 v0" (Version Data), the old 3DNUS v1.9 by ground works fine for downloading these.

**Comment by zoltx23** [comment]
3DNUS 2.6+ uses the new YLS Parser by MarcusD. I'll have to get him to refine it again. It's most likely not parsing the .csv file correctly. 

I am sorry for any problems. 
Also, some system titles have always had issues when downloading and packing. Try using both the new3DS and old3DS title-lists.

**Comment by v0idst4r** [comment]
Np. Yeah I tried both title lists.

**Comment by zoltx23** [comment]
Then this is confirmed to be a bug. I will get MarcusD to fix this issue. Since he designed the parser.

**Comment by MarcuzD** [comment]
it should write at least *something* to the output textbox, no? can you please post the output of the textbox? or if an error shows up then please screenshot that too. also, make sure "pack as cia" is checked and you have make_cdn_cia.exe next to 3DNUS.exe

**Comment by zoltx23** [comment]
There should be a label with the text "Dump Log." Press that. Before that though, in the settings make sure "Dump System Info" is checked.

**Comment by v0idst4r** [comment]
It acts like the title doesn't exist. Try it for yourself, unfortunately I'm not at home right now.

**Comment by zoltx23** [comment]
Is the actual title ID located within the Title Database? 

I you said that it was able to be downloaded in 3DNUS 1.9; then this has to be an issue with the parser.

**Comment by MarcuzD** [comment]
[the stupidity hurts](https://github.com/zoltx23/3DNUS/blob/unfinished/Source/3DNUS_Material_Source/3DNUS%20Material%20Edition/3DNUS%20Material%20Edition/FormMain.cs#L315) 😭 
I'm sorry for being such dummy such a long time ago... it should be
> `([0-9a-fA-F]{16})([\s_]*v?(\d+))?`

**Comment by xKyup** [comment]
ecks dee

**Comment by zoltx23** [comment]
I have replaced the current Regex with the one that MarcusD proposed. 
I will be compiling a build tonight and see if the Title downloads. 

If it does, I will release the build as 3.2.1 (Nightly)

**Comment by v0idst4r** [comment]
I tested the new regexp and it matches these titles, the old one doesn't. Closing.
