### ISSUE TITLE
3DNUS | Updater 

### ISSUE THREAD

**Issue by zoltx23** [zoltx23/3DNUS#3]
Currently the Updater does not download the Appropriate build. But, this will soon be fixed! 
Most likely in the Next Pre-Release! 

## What to expect: 

- An Improved Updater, and Extension Manager 
- Improved Compatibility (Planning on making an App that'll run on NET 4.1, then check to see if the Proper Framework, and components are ready)  
- And of course, some bug fixes.

**Comment by zoltx23** [comment]
Issue is currently being worked on!

**Comment by MarcuzD** [comment]
I'll rewrite the updater at [/unusable](/zoltx23/3DNUS/tree/unusable)

**Comment by zoltx23** [comment]
When i try to run the Dev Build that you compiled (From the Debug Folder) It closes upon showing the Main form. I there something that's causing this?

**Comment by zoltx23** [comment]
I see you made a Translator. I'll see if i can get some work done on that for you!

**Comment by MarcuzD** [comment]
I think the old version of 3DNUS is obsolete, so I'll close this issue.

Since the Material Edition is written from scratch, it'll include a reworked updater soon.
