### ISSUE TITLE
Directory Error

### ISSUE THREAD

**Issue by zoltx23** [zoltx23/3DNUS#4]
When downloading some Firmware's, you may get an Error such as this: 

The directory is *not* empty (Possibly \Temp); 
This may be able to be fixed by adding a "Try & Catch Exception"  
**DUMPED_JIT_ERROR:** 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at _3DNUS_Material_Edition.FormMain.singledownload(UInt64 id, Int32 version)
   at _3DNUS_Material_Edition.FormMain.firmwdownload(YLS_Sysver sys, Char region)
   at _3DNUS_Material_Edition.FormMain.materialFlatButton1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
3DNUS Material Edition
    Assembly Version: 2.7.0.3
    Win32 Version: 2.7.0.3
    CodeBase: file:///C:/Users/Luke/Desktop/Applications/3DNUS/3DNUS%20Material%20Edition.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MaterialSkin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Luke/Desktop/Applications/3DNUS/MaterialSkin.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

===========================================================================

**Below is the Dumped log when downloading FW 7.1 --> 11.0 USA** 

--Log Dump Start--

SystemOS: Microsoft Windows NT 6.2.9200.0

Program Version: 2.7.0.4

Debug State: Uknown

Time Dumped: 6/30/2016 3:55:49 PM

---------------------------------------
Console:  6/30/2016 3:54:33 PM
Checking title database, please wait...
Downloading Firmware: 7.1.0-999U

Downloading 0004001000021000 v6157...
Title has 2 contents
Downloading complete
Downloading complete
Packing as .cia ...
Done.

Downloading 0004001000021100 v2051...
Title has 1 content
Downloading complete
Packing as .cia ...
Done.

Downloading 0004001000021200 v2064...
Title has 2 contents
Downloading complete
Downloading complete
Packing as .cia ...
Done.

Downloading 0004001000021300 v2051...
Title has 1 content
Downloading complete
Packing as .cia ...
Done.

Downloading 0004001000021400 v3088...
Title has 2 contents
Downloading complete
Downloading complete
Packing as .cia ...

**Comment by MarcuzD** [comment]
I guess this only happens if something is accessing a file in the `tmp` folder, so it can't delete the directory, and throws this rather unhelpful error. This should never happen unless the user has either opened a file, or a program is locking the directory itself (like cmd).

**Comment by MarcuzD** [comment]
Yes, the problem no longer exists. Instead of crashing, the inability to delete \\tmp is semi-silently ignored now.
