### ISSUE TITLE
Error thrown when trying to download any updates for the N3DS that prevents the update from downloading

### ISSUE THREAD

**Issue by Direlynx** [zoltx23/3DNUS#5]
Steps to reproduce: Open 3DNUS, Click "New 3DS" button, type in any update, then hit begin download.

Error:
http://pastebin.com/3PS6fWTg

OS: Windows 8.1 x64
Version of 3DNUS: Any, including the newest nightly and release builds

**Comment by MarcuzD** [comment]
Oh boy, please no! Gotta fix the database parser again :/
