### ISSUE TITLE
Unhandled Exception when downloading ANY Firmware version

### ISSUE THREAD

**Issue by OpusIkahn** [zoltx23/3DNUS#8]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
   at _3DNUS_Material_Edition.FormMain.firmwdownload(YLS_Sysver sys, Char region) in C:\Documents and Settings\MarcusD\Desktop\HacknikNUS\3DNUS\Source\3DNUS_Material_Source\3DNUS Material Edition\3DNUS Material Edition\FormMain.cs:line 163
   at _3DNUS_Material_Edition.FormMain.materialFlatButton1_Click(Object sender, EventArgs e) in C:\Documents and Settings\MarcusD\Desktop\HacknikNUS\3DNUS\Source\3DNUS_Material_Source\3DNUS Material Edition\3DNUS Material Edition\FormMain.cs:line 308
   at System.Windows.Forms.Button.PerformClick()
   at _3DNUS_Material_Edition.FormMain.<.ctor>b__2(Object _dmy_sndr__, KeyEventArgs _keyevt) in C:\Documents and Settings\MarcusD\Desktop\HacknikNUS\3DNUS\Source\3DNUS_Material_Source\3DNUS Material Edition\3DNUS Material Edition\FormMain.cs:line 100
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
3DNUS Material Edition
    Assembly Version: 2.8.0.1
    Win32 Version: 2.8.0.1
    CodeBase: file:///C:/Users/Matthew/Desktop/PKHEXIN/3DNUS/3DNUS%20Material%20Edition.exe
----------------------------------------
MaterialSkin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Matthew/Desktop/PKHEXIN/3DNUS/MaterialSkin.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36366 built by: FX452RTMLDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36366 built by: FX452RTMLDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36366 built by: FX452RTMLDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36366 built by: FX452RTMLDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36366 built by: FX452RTMLDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.36366 built by: FX452RTMLDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AxInterop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Matthew/Desktop/PKHEXIN/3DNUS/AxInterop.WMPLib.DLL
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Matthew/Desktop/PKHEXIN/3DNUS/Interop.WMPLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

____________________________________________________________

How can I fix this? It just hangs after I press continue.

**Comment by MarcuzD** [comment]
This is already fixed, see #7 for a fixed build
