### ISSUE TITLE
Cannot update titlelist

### ISSUE THREAD

**Issue by johnwraight** [zoltx23/3DNUS#9]
"cant acquire the title list.
you can still download titles, but firmware downloading is not possible,
thus the downloading will be aborted"

please help.
what do I need to do to download firmware?

**Comment by MarcuzD** [comment]
3DNUS downloads the title list from mtheall.com, but sadly it's dead. There's not much we can do about it :/

**Comment by zoltx23** [comment]
mtheall is back online; but 3DNUS is still dead. Sorry for any inconvenience.
